# -*- coding: utf-8 -*-
"""Kmean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-jHNcEN7vSWYb8O_JV7fY5xqnA36OXX
"""



from google.colab import drive 
drive.mount('/content/drive')

pip install -q keras

"""# New Section"""

import keras

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np

Foldername = '/content/drive/My Drive/Foldername/'
X = np.loadtxt(Foldername+"cardiacData.txt", delimiter=',')
plt.scatter(X[:, 0], X[:, 1])

"""Finding K bY Plotting the elbow"""

WCSS = []
K = range(1,10)
for this_k in K:
  kmeanModel = KMeans(n_clusters= this_k)
  kmeanModel.fit(X)
  WCSS.append(kmeanModel.inertia_)

# pot the elbow
plt.figure()
plt.plot(K, WCSS, 'bx-')
plt.xlabel('k')
plt.ylabel('WCSS')
plt.title('The Elbow method showing the optimal k')

"""The optimun k from the graph is 5
Now we will do the K-Means Clustering
"""

#Initializing our KMeans
kmeans = KMeans(n_clusters=6)
#Fitting with inputs
kmeans = kmeans.fit(X)
#Predicting the clusters
labels = kmeans.predict(X)
#Getting the cluster centers
C = kmeans.cluster_centers_

plt.figure()
plt.scatter(X[:, 0], X[:, 1], c=labels)
#plt.scatter(X[:, 0], X[:, 1], c=labels)
plt.scatter(C[:, 0], C[:, 1], marker='*', c='#050505', s=1000)